name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main
      - '*.x'

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    # Until v6 is released
    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@dce2d3baa0217603bb24af73e387f1e9659edf6f
    with:
      autoMerge: true
      mergeArguments: --auto --squash
